### PC99 (x64)
[build.pc99]
cross_compiler_prefix = "x86_64-linux-gnu-"

[build.pc99.debug]
make_root_task = "cargo build --target=x86_64-unknown-linux-gnu"
root_task_image = "target/x86_64-unknown-linux-gnu/debug/example"

[build.pc99.release]
make_root_task = "cargo build --target=x86_64-unknown-linux-gnu --release"
root_task_image = "target/x86_64-unknown-linux-gnu/release/example"

### Sabre (ARMv7 imx6)
[build.sabre]
cross_compiler_prefix = "arm-linux-gnueabihf-"

[build.sabre.debug]
make_root_task = "cargo build --target=armv7-unknown-linux-gnueabihf"
root_task_image = "target/armv7-unknown-linux-gnueabihf/debug/example"

[build.sabre.release]
make_root_task = "cargo build --target=armv7-unknown-linux-gnueabihf --release"
root_task_image = "target/armv7-unknown-linux-gnueabihf/release/example"

### TX1 Virt (aarch64)
[build.virt]
cross_compiler_prefix = "aarch64-linux-gnu-"

[build.virt.debug]
make_root_task = "cargo build --target=aarch64-unknown-linux-gnu -v"
root_task_image = "target/aarch64-unknown-linux-gnu/debug/example"

[build.virt.release]
make_root_task = "cargo build --target=aarch64-unknown-linux-gnu --release"
root_task_image = "target/aarch64-unknown-linux-gnu/release/example"

[sel4]
# Specifically selected to support the virtualized aarch64 tx1-like platform, virt
kernel = { git = "https://github.com/seL4/sel4.git", branch = "master" }
tools = { git = "https://github.com/seL4/sel4_tools.git", branch = "master" }
util_libs = { git = "https://github.com/seL4/util_libs.git", branch = "master" }
musl_libc = { git = "https://github.com/seL4/musllibc.git", branch = "sel4" }

### arch

[sel4.config.x86]
KernelArch = 'x86'

[sel4.config.arm]
KernelArch = 'arm'
KernelIPCBufferLocation = 'threadID_register'

### sel4_arch

[sel4.config.x86_64]
KernelSel4Arch = 'x86_64'
KernelX86Sel4Arch = 'x86_64'

[sel4.config.aarch32]
KernelSel4Arch = 'aarch32'
KernelArmSel4Arch = 'aarch32'

[sel4.config.aarch64]
KernelSel4Arch = 'aarch64'
KernelArmSel4Arch = 'aarch64'

### platform

[sel4.config.pc99]
KernelPlatform = 'pc99'
KernelX86MicroArch = 'nehalem'
LibPlatSupportX86ConsoleDevice = 'com1'
KernelVTX = false
KernelX86DangerousMSR = false
KernelX86IBPBOnContextSwitch = false
KernelX86IBRSMode = 'ibrs_none'
KernelX86RSBOnContextSwitch = false


[sel4.config.sabre]
KernelPlatform = 'imx6'
KernelHaveFPU = true

[sel4.config.virt]
KernelPlatform = 'qemu-arm-virt'
KernelHaveFPU = true
ElfloaderImage = 'elf'
KernelArmHypervisorSupport = true

### Build mode

[sel4.config.debug]
KernelPrinting = true
KernelDebugBuild = true
KernelVerificationBuild = false

[sel4.config.release]
KernelPrinting = false
KernelDebugBuild = false
KernelOptimisation = '-O2'


[sel4.config]
KernelColourPrinting = true
KernelUserStackTraceLength = 16
KernelVerificationBuild = false
KernelBenchmarks = 'none'
KernelFastpath = true
LibSel4FunctionAttributes = 'public'
KernelNumDomains = 1
HardwareDebugAPI = false
KernelFWholeProgram = false
KernelResetChunkBits = 8
KernelNumPriorities = 256
KernelStackBits = 12
KernelTimeSlice = 5
KernelTimerTickMS = 2
KernelMaxNumNodes = 1
KernelRetypeFanOutLimit = 16384
KernelRootCNodeSizeBits = 19
KernelMaxNumBootinfoUntypedCaps = 230
KernelSupportPCID = false
KernelDebugDisablePrefetchers = false
KernelExportPMCUser = false
KernelFPU = 'FXSAVE'
KernelFPUMaxRestoresSinceSwitch = 64
KernelFSGSBase = 'msr'
KernelHugePage = true
KernelIOMMU = false
KernelIRQController = 'IOAPIC'
KernelIRQReporting = true
KernelLAPICMode = 'XAPIC'
KernelMaxNumIOAPIC = 1
KernelMaxNumWorkUnitsPerPreemption = 100
KernelMultiboot1Header = true
KernelMultiboot2Header = true
KernelMultibootGFXMode = 'none'
KernelSkimWindow = true
KernelSyscall = 'syscall'
KernelXSaveSize = 576
LinkPageSize = 4096
